name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore aecci-web/backend/AecciWeb.csproj

      - name: Build
        run: dotnet build aecci-web/backend/AecciWeb.csproj --no-restore

      - name: Test and collect coverage
        run: dotnet test aecci-web/AecciWeb.Tests/AecciWeb.Tests.csproj --collect:"XPlat Code Coverage"

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: '**/coverage.cobertura.xml'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=GigioCR_AEECI_Web
            -Dsonar.organization=gigiocr
            -Dsonar.coverageReportPaths=aecci-web/AecciWeb.Tests/TestResults/**/coverage.cobertura.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}